// Hand-authored anatomical shape data for the front/back body map figures.
// See Figure.tsx for how these become <path> elements. Coordinates share a
// 0 0 300 700 viewBox, centerline x=150. Bilateral muscles are authored once
// for the LEFT half (x < 150) and mirrored across the centerline at render
// time (see Figure.tsx), so a single shape definition drives both sides of
// the body. Centerline silhouette pieces (head, hair, neck, torso) are built
// with `symmetricContour`, which walks the LEFT contour as cubic-bezier
// segments and mirrors it back up the right side algorithmically, so the two
// halves can never drift out of symmetry.
//
// All contours are cubic beziers (no straight-edge polygons) except joints
// that are genuinely flat in cross-section (wrist/ankle cuffs).
//
// Proportions target ~7.5 head-heights: head 14-112 (h=98), shoulder width
// ~196 (2.2 head-widths), knees ~3/4 down the leg, hands reaching mid-thigh.

import type { SubMuscleId } from "@/data/taxonomy";

export type MuscleShape = { kind: "path"; d: string };

export interface MuscleRegion {
  id: SubMuscleId;
  /** One or more shapes sharing this muscle id (e.g. quads_vasti renders
   * as two teardrops per leg — lateral + medial heads). */
  shapes: MuscleShape[];
  /** If true, this region is authored for the left half only and gets a
   * mirrored copy rendered across the centerline. Centerline-spanning
   * regions (abs, traps, spine) set this to false. */
  mirror: boolean;
}

function path(d: string): MuscleShape {
  return { kind: "path", d };
}

// ---------------------------------------------------------------------------
// Geometry helpers — parametric, so shapes stay smooth/curved and symmetric
// without hand-transcribing mirrored control points.
// ---------------------------------------------------------------------------

const CX = 150;
const mirrorX = (x: number) => 2 * CX - x;

/** A cubic-bezier segment: [c1x, c1y, c2x, c2y, ex, ey]. */
type Seg = readonly [number, number, number, number, number, number];

/**
 * Builds a closed, left-right symmetric contour. `segments` describes the
 * LEFT half only, walking from a centerline top point down to a centerline
 * bottom point (the final segment's end point must have x === CX). The
 * right half is generated by mirroring each segment's control points and
 * endpoints back up in reverse, guaranteeing perfect symmetry.
 */
function symmetricContour(topY: number, segments: readonly Seg[]): string {
  const left = segments.map(([c1x, c1y, c2x, c2y, ex, ey]) => `C${c1x},${c1y} ${c2x},${c2y} ${ex},${ey}`).join(" ");
  const pts: Array<readonly [number, number]> = [[CX, topY], ...segments.map((s) => [s[4], s[5]] as const)];
  const rev = [...segments].reverse();
  const right = rev
    .map((seg, i) => {
      const [, , c2x, c2y, , ] = seg;
      const c1x = seg[0];
      const c1y = seg[1];
      const prev = pts[pts.length - 2 - i];
      return `C${mirrorX(c2x)},${c2y} ${mirrorX(c1x)},${c1y} ${mirrorX(prev[0])},${prev[1]}`;
    })
    .join(" ");
  return `M${CX},${topY} ${left} ${right} Z`;
}

/**
 * A closed, organic "leaf"/teardrop shape between a narrow top point and a
 * wider bottom point — used for the long limb muscles (biceps, hamstrings,
 * calves, ...) instead of plain ellipses so they read as tapered bellies
 * rather than ovals.
 */
function teardrop(cx: number, cy: number, rx: number, ry: number, bulge = 0.2): string {
  const topY = cy - ry;
  const botY = cy + ry;
  const midY = cy + ry * bulge;
  return (
    `M${cx},${topY} ` +
    `C${cx + rx * 0.75},${topY + ry * 0.25} ${cx + rx},${midY - ry * 0.35} ${cx + rx * 0.9},${midY} ` +
    `C${cx + rx * 0.65},${midY + ry * 0.45} ${cx + rx * 0.3},${botY} ${cx},${botY} ` +
    `C${cx - rx * 0.3},${botY} ${cx - rx * 0.65},${midY + ry * 0.45} ${cx - rx * 0.9},${midY} ` +
    `C${cx - rx},${midY - ry * 0.35} ${cx - rx * 0.75},${topY + ry * 0.25} ${cx},${topY} Z`
  );
}

// ---------------------------------------------------------------------------
// Background silhouette (non-interactive guide, drawn behind/around muscles)
// ---------------------------------------------------------------------------

const TORSO_D = symmetricContour(140, [
  [128, 140, 70, 142, 48, 153], // shoulder cap
  [46, 166, 53, 178, 62, 189], // armpit indent
  [69, 201, 65, 214, 69, 231], // ribcage / lat
  [73, 248, 87, 261, 106, 275], // taper to waist
  [114, 285, 84, 296, 80, 314], // flare to hip
  [78, 328, 96, 338, 150, 342], // curve to groin center
]);

const NECK_D = symmetricContour(103, [
  [144, 109, 136, 117, 133, 129], // jaw down the side of a thick neck column
  [133, 135, 141, 139, 150, 140], // short tuck into the shoulder line
]);

const HEAD_D = symmetricContour(10, [
  [120, 11, 109, 22, 109, 44], // crown to temple
  [109, 64, 113, 80, 124, 95], // temple to jaw
  [140, 102, 148, 103, 150, 103], // rounded jaw to chin (flatter, less pointed)
]);

const HAIR_D = symmetricContour(4, [
  [122, 4, 109, 8, 108, 24], // apex to hairline side
  [107, 33, 124, 30, 150, 26], // hairline back to widow's peak
]);

// Per-limb pieces are authored for the LEFT side and mirrored by Figure.tsx.
const ARM_LEFT_D =
  "M56,149 C39,154 30,170 28,191 C26,216 29,241 33,264 C35,279 37,288 40,299 " +
  "C35,319 33,340 35,365 C36,385 39,401 44,414 L55,416 " +
  "C52,401 50,385 50,365 C49,341 51,319 49,299 " +
  "C46,288 44,279 46,264 C43,241 45,216 49,192 C52,172 56,157 62,150 Z";

const LEG_LEFT_D =
  "M92,336 C79,371 76,411 81,451 C83,469 87,479 92,487 " +
  "C85,501 81,522 84,551 C86,577 88,597 91,613 C92,619 93,623 95,627 L108,627 " +
  "C105,619 103,608 101,595 C98,575 96,554 99,530 C101,510 103,498 106,487 " +
  "C109,472 111,455 112,440 C114,410 116,375 120,340 C118,338 115,337 112,336 Z";

const HAND_LEFT_D = (() => {
  // Palm blob + four fanned finger leaves + a shorter thumb, rooted at the
  // wrist. All curves — no straight polygon edges.
  const palm =
    "M40,414 C31,419 26,430 27,443 C28,455 33,463 41,467 C50,471 60,469 65,462 " +
    "C68,455 68,443 65,431 C62,420 56,414 47,412 Z";
  const finger = (bx: number, by: number, len: number, w: number, angle: number) => {
    const rad = (angle * Math.PI) / 180;
    const tx = bx + len * Math.sin(rad);
    const ty = by + len * Math.cos(rad);
    const nx = Math.cos(rad) * w;
    const ny = -Math.sin(rad) * w;
    return (
      `M${bx - nx},${by - ny} C${bx - nx * 0.6},${by - ny * 0.6 + len * 0.5} ${tx - nx * 0.15},${ty - len * 0.15} ${tx},${ty} ` +
      `C${tx + nx * 0.15},${ty - len * 0.15} ${bx + nx * 0.6},${by + ny * 0.6 + len * 0.5} ${bx + nx},${by + ny} Z`
    );
  };
  const fingers = [
    finger(32, 465, 30, 4.4, -20),
    finger(39, 470, 36, 5, -6),
    finger(48, 471, 34, 4.6, 8),
    finger(56, 466, 28, 4, 22),
  ].join(" ");
  const thumb = finger(31, 429, 17, 5.5, -52);
  return `${palm} ${fingers} ${thumb}`;
})();

const FOOT_LEFT_D =
  "M93,620 C77,627 68,641 71,655 C74,667 85,677 102,681 C116,684 131,681 138,672 " +
  "C141,665 137,655 128,647 C120,641 114,630 110,620 Z";

export const SILHOUETTE = {
  head: path(HEAD_D),
  hair: path(HAIR_D),
  neck: path(NECK_D),
  torso: path(TORSO_D),
  armLeft: path(ARM_LEFT_D),
  legLeft: path(LEG_LEFT_D),
  handLeft: path(HAND_LEFT_D),
  footLeft: path(FOOT_LEFT_D),
} as const;

export const SILHOUETTE_FRONT = SILHOUETTE;
export const SILHOUETTE_BACK = SILHOUETTE;

/** Non-interactive detail strokes drawn over the fills (ab segmentation,
 * finger creases, spine hint, ...) purely for the "line-art anatomy" look;
 * these are outline-only, never separately hoverable. */
export const DETAIL_LINES_FRONT: readonly string[] = [
  // Ab segmentation: vertical linea alba + three horizontal tendon lines.
  "M150,232 L150,300",
  "M132,250 C140,253 160,253 168,250",
  "M130,268 C140,271 160,271 170,268",
  "M132,286 C140,288 160,288 168,286",
  // Sternum midline hint on chest.
  "M150,132 L150,222",
];

export const DETAIL_LINES_BACK: readonly string[] = [
  // Spine hint above/below the erector shape.
  "M150,140 L150,222",
  // Shoulder-blade hint lines.
  "M118,158 C126,172 132,188 128,206",
  "M182,158 C174,172 168,188 172,206",
];

// ---------------------------------------------------------------------------
// Front view muscles
// ---------------------------------------------------------------------------

export const FRONT_REGIONS: readonly MuscleRegion[] = [
  { id: "front_delt", mirror: true, shapes: [path(teardrop(53, 157, 20, 25, 0.15))] },
  { id: "side_delt", mirror: true, shapes: [path(teardrop(26, 169, 10, 19, 0.05))] },

  {
    id: "upper_chest",
    mirror: true,
    shapes: [
      path(
        "M150,143 C128,141 104,142 80,151 C75,157 74,164 77,170 " +
          "C79,172 82,172 85,170 C106,161 128,157 150,158 Z",
      ),
    ],
  },
  {
    id: "mid_chest",
    mirror: true,
    shapes: [
      path(
        "M150,160 C126,159 100,162 76,172 C72,181 72,191 77,200 " +
          "C80,202 84,201 87,198 C108,187 130,182 150,182 Z",
      ),
    ],
  },
  {
    id: "lower_chest",
    mirror: true,
    shapes: [
      path(
        "M150,184 C128,183 104,187 82,196 C81,205 85,214 93,221 " +
          "C97,223 102,222 106,219 C122,208 138,201 150,199 Z",
      ),
    ],
  },

  { id: "biceps", mirror: true, shapes: [path(teardrop(41, 225, 12, 42, 0.25))] },
  { id: "brachialis_brachioradialis", mirror: true, shapes: [path(teardrop(40, 281, 10, 19, 0.2))] },
  { id: "forearms", mirror: true, shapes: [path(teardrop(43, 343, 12, 50, 0.3))] },

  {
    id: "rectus_abdominis",
    mirror: false,
    shapes: [
      path(
        "M150,225 C136,225 126,229 122,236 C118,255 118,278 124,296 " +
          "C130,304 140,308 150,309 C160,308 170,304 176,296 " +
          "C182,278 182,255 178,236 C174,229 164,225 150,225 Z",
      ),
    ],
  },
  {
    id: "obliques",
    mirror: true,
    shapes: [
      path(
        "M120,232 C106,238 96,250 92,266 C91,278 94,289 102,296 " +
          "C110,298 117,297 122,293 C119,275 118,253 120,232 Z",
      ),
    ],
  },

  { id: "quads_rectus_femoris", mirror: true, shapes: [path(teardrop(113, 418, 17, 60, 0.15))] },
  {
    id: "quads_vasti",
    mirror: true,
    shapes: [path(teardrop(88, 404, 15, 46, 0.15)), path(teardrop(134, 448, 12, 30, 0.15))],
  },
  { id: "adductors", mirror: true, shapes: [path(teardrop(145, 376, 6, 36, 0.3))] },
];

// ---------------------------------------------------------------------------
// Back view muscles
// ---------------------------------------------------------------------------

export const BACK_REGIONS: readonly MuscleRegion[] = [
  { id: "rear_delt", mirror: true, shapes: [path(teardrop(53, 157, 20, 25, 0.15))] },
  { id: "side_delt", mirror: true, shapes: [path(teardrop(26, 169, 10, 19, 0.05))] },

  {
    id: "upper_traps",
    mirror: false,
    shapes: [
      path(
        "M150,127 C132,128 112,133 96,142 C102,148 112,153 124,156 " +
          "C133,150 141,146 150,145 C159,146 167,150 176,156 " +
          "C188,153 198,148 204,142 C188,133 168,128 150,127 Z",
      ),
    ],
  },
  {
    id: "mid_traps_rhomboids",
    mirror: false,
    shapes: [
      path(
        "M150,158 C137,159 124,163 114,171 C111,186 113,202 119,214 " +
          "C129,220 139,223 150,224 C161,223 171,220 181,214 " +
          "C187,202 189,186 186,171 C176,163 163,159 150,158 Z",
      ),
    ],
  },
  {
    id: "lower_traps",
    mirror: false,
    shapes: [
      path("M150,226 C143,226 136,228 132,232 C134,247 139,260 150,268 C161,260 166,247 168,232 C164,228 157,226 150,226 Z"),
    ],
  },
  {
    id: "spinal_erectors",
    mirror: true,
    shapes: [
      path(
        "M150,228 C145,228 141,232 140,238 C137,266 137,296 141,322 " +
          "C143,328 147,331 150,332 L150,228 Z",
      ),
    ],
  },

  {
    id: "lats",
    mirror: true,
    shapes: [
      path(
        "M120,176 C102,182 86,194 79,212 C76,228 80,244 90,256 " +
          "C99,264 110,267 121,265 C127,236 126,204 122,177 Z",
      ),
    ],
  },

  { id: "triceps_long", mirror: true, shapes: [path(teardrop(47, 214, 8, 32, 0.2))] },
  { id: "triceps_lat_med", mirror: true, shapes: [path(teardrop(37, 224, 12, 48, 0.25))] },

  { id: "hamstrings", mirror: true, shapes: [path(teardrop(112, 418, 16, 60, 0.15))] },
  { id: "glute_max", mirror: true, shapes: [path(teardrop(102, 352, 26, 32, -0.05))] },
  { id: "glute_med", mirror: true, shapes: [path(teardrop(83, 324, 11, 16, 0.1))] },

  { id: "gastrocnemius", mirror: true, shapes: [path(teardrop(112, 548, 15, 42, 0.05))] },
  { id: "soleus", mirror: true, shapes: [path(teardrop(114, 605, 10, 26, 0.3))] },
];

export const VIEW_BOX = "0 0 300 700";
